# syntax=docker/dockerfile:1

FROM postgres:17
WORKDIR /app
COPY . .
# COPY entrypoint.sh /usr/local/bin/entrypoint.sh
# RUN chmod 755 /usr/local/bin/entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]

# RUN psql -Y postgres -f "./mock-data-person.sql"
# CMD ["psql -Y postgres -f ./mock-data-person.sql"]
# EXPOSE 3000