
pipeline {
    agent { docker { image 'golang:1.24.2-alpine3.21' } }
    stages {
        stage('build') {
            steps {
                sh 'go version'

                retry(3) { sh 'go env' }
            }
        }

        stage('test') {
            steps {
                timeout(time: 3, unit: 'MINUTES') { sh 'pwd' }
                // throw new Exception("Throw to stop pipeline")
            }
        }
    }

    post {
        always {
            script {
                echo 'This will always run'
            }
        }
        success {
            script {
                echo 'This will only run on success'
            }
        }
        failure {
            script {
                echo 'This will only run on failure'
            }
        }
        unstable {
            script {
                echo 'This will only run if the build is unstable'
            }
        }
    }
}
