name: advent-calendar

on:
  pull_request:
    branches: [ "advent-calendar" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

 ###########################################################################
      ############### Client
      ###########################################################################
    - name: install
      id: install
      working-directory: ./client
      run: make npm/install
      continue-on-error: false

    - name: lint
      id: lint
      run: make lint/application
      continue-on-error: false

    # - name: test
    #   id: test
    #   run: make test/application
    #   continue-on-error: false

    - name: build
      id: build
      working-directory: ./client
      run: make build/application
      continue-on-error: false

    - name: rewrite
      id: rewrite
      working-directory: ./client
      run: make rewrite/extension
      continue-on-error: false

    # - name: clear s3
    #   id: clear
    #   working-directory: ./client
    #   run: make s3/clean
    #   continue-on-error: false

    # - name: sync html files
    #   id: synchtml
    #   working-directory: ./client
    #   run: make s3/push/html
    #   continue-on-error: false

    # - name: sync remaining files
    #   id: syncremaining
    #   working-directory: ./client
    #   run: make s3/push/remaining
    #   continue-on-error: false

    # - name: refresh cloudfront
    #   id: cloudfront
    #   working-directory: ./client
    #   run: make cloudfront/cache/refresh
    #   continue-on-error: false
